### ISSUE TITLE
Meteor 0.5.8 appears to break the todo example

### ISSUE THREAD

**Issue by dwtowner** [steveluscher/knockout.meteor#7]
This looks like a great project, but it doesn't seem to be working with current meteor (0.5.8). The todos example just shows the three titles (Do it now, Finished, Unfinished), but none of the todos themselves. 

(Google Chrome 22, Ubuntu 10.04).

**Comment by steveluscher** [comment]
Good call. Meteor completely changed the dependency tracking API while I had my back turned. I just pushed version 0.4.0 of knockout.meteor. Enjoy!
